project:
  type: website
  output-dir: docs #웹사이트를 docs라는 폴더에 넣어라

website:
  title: "박수빈의 포트폴리오"
  description: "박수빈의 작업 및 프로젝트 포트폴리오"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: blog.qmd
        text: Blog
      
    right:
      - text: GitHub
        href: https://github.com/nebuss/mywebsite

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    
    highlight: github



